### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by LeBronoMars** [florent37/MaterialLeanBack#10]
- Followed every step but still getting this exception

Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

E/AndroidRuntime( 5763): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 5763): 	at com.github.florent37.materialleanback.line.LineAdapter.onCreateViewHolder(LineAdapter.java:53)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
E/AndroidRuntime( 5763): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)

**Comment by Hitexroid** [comment]
**please help !**

**Comment by Hitexroid** [comment]
Please find error 👍 (very important)
![screenshot 170](https://cloud.githubusercontent.com/assets/19854097/20837006/50e09b1c-b8b7-11e6-8c3b-754c8c0e4896.png)


`    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup viewGroup, int type) {
        View view;
        switch (type) {
            case PLACEHOLDER_START:
                view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.mlb_placeholder, viewGroup, false);
                return new PlaceHolderViewHolder(view, false, settings.paddingTop);
            case PLACEHOLDER_END:
                view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.mlb_placeholder, viewGroup, false);
                return new PlaceHolderViewHolder(view, false, settings.paddingBottom);
            case CELL:
                view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.mlb_row, viewGroup, false);
                return new LineViewHolder(view, adapter, settings, customizer);
            default:
                if(adapter != null && adapter.isCustomView(type)){
                    return adapter.getCustomViewForRow(viewGroup,type);
                }
        }
        return null;
    }`
